# Generated by Django 3.2.4 on 2021-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='URL',
            field=models.CharField(default='https://605f4c3045aa8bd5bfeed529--vigorous-lovelace-8cd4cb.netlify.app/', max_length=100),
            preserve_default=False,
        ),
    ]
